// TODO Add more orn replace entirely the facts below for your chosen history domain
// Include at least 10 distinct facts with a 4-digit year included in the text for each
/*"The field of AI is considered to have its origin in 1950, with publication of British mathematician Alan Turing's paper, Computing Machinery and Intelligence.",
"The term, Artificial Intelligence, was coined in 1956 by mathematician and computer scientist John McCarthy, at Dartmouth College, in New Hampshire.",
"In 1997, a chess-playing program named Deep Blue, developed by IBM, beat the reigning world chess champion.",
"A so-called AI Winter occurred in 1974, when funding was cut after Speech Understanding research did not live up to its promise.",
"A driverless robotic car named Stanley, engineered by Sebastian Thrun's Stanford Racing team, sped through the Mojave desert at 22 miles per hour to win the 2005 Darpa Grand Challenge.",
"Replace me and add some more facts!"*/
module.exports = {
    "FACTS_EN": [
        "2016 – Buenos Aires Forum in Buenos Aires is expected to be completed, Zaha Hadid dies.",
		"2015 – Shanghai Tower in Shanghai, the tallest building in China and the second-tallest in the world, projected for completion, Charles Correa dies.",
		"2013 – One World Trade Center dedicated in New York City.",
		"2012 – Oscar Niemeyer dies.",
		"2011 – Al Hamra Tower, the tallest skyscraper in Kuwait, completed.",
		"2010 – Burj Khalifa became the tallest man-made structure in the world, at 828 metres (2,717 ft).",
		"2009 – CityCenter opens on the Las Vegas Strip in Paradise, Nevada. This project is the largest privately funded construction project in the history of the United States.",
		"2008 – 'Water Cube', 'Birds Nest', South Railway Station, and other buildings in Beijing, completed for the 2008 Summer Olympics.",
		"2007 – Tarald Lundevall completes the Oslo Opera House in Oslo, Norway.",
		"2006 – Construction begins on the Freedom Tower, on the site of the former World Trade Center.",
		"2005 – Casa da Música opens in Porto, Portugal, designed by the Dutch architect Rem Koolhaas with Office for Metropolitan Architecture.",
		"2004 – 30 St Mary Axe (also known as 'the Gherkin' and the Swiss Re Building), designed by Norman Foster, completed in the City of London.",
		"2003 – Taipei 101, designed by C.Y. Lee & Partners the worlds tallest building from 2004–2010 is topped out.",
		"2002 – Simmons Hall dormitory, designed by architect Steven Holl, completed at the Massachusetts Institute of Technology.",
		"2001 – Jewish Museum Berlin designed by Daniel Libeskind opens to the public.",
		"2000 – The Emirates Towers are both completed in Dubai.",
		"1999 – Jewish Museum Berlin, designed by Daniel Libeskind is completed.",
		"1998 – Petronas Twin Towers, Kuala Lumpur, Malaysia, designed by César Pelli is completed. World tallest building 1998–2004.",
		"1998 – Kiasma Museum of Contemporary Art by Steven Holl Architects, opens to the public.",
		"1997 – Guggenheim Museum Bilbao designed by Frank Gehry.",
		"1996 – Oscar Niemeyer completes the Niterói Contemporary Art Museum in Brazil.",
		"1996 – Aronoff Center for Design and Art, University of Cincinnati completed by Peter Eisenman.",
		"1995 – Steven Holl Architects begin construction of St. Ignatius Chapel at Seattle University.",
		"1994 – Building of the Basel Signal Box by Herzog and de Meuron",
		"1993 – The Umeda Sky Building in Osaka City, Japan is completed.",
		"1992 – The Bank of America Corporate Center in Charlotte, North Carolina is completed.",
		"1991 – Stansted Airport terminal building in Essex, England, designed by Norman Foster, is completed.",
		"1990 – Frederick Weisman Museum of Art, University of Minnesota completed by Frank Gehry.",
		"1989 – I. M. Pei's pyramid addition to the Louvre is opened.",
		"1988 – MOMA Exhibition called Deconstructivist architecture opens.",
		"1987 – The Riga Radio & TV Tower in Riga, Latvia is completed.",
		"1986 – The Lloyd's Building in London, designed by Richard Rogers, is completed.",
		"1985 – The HSBC Headquarters Building in Hong Kong, China by Norman Foster, is completed.",
		"1984 – Philip Johnson's AT&T Building opens in New York City",
		"1983 – Xanadu House in Kissimmee opened.",
		"1982 – Design competition is held for the Parc de la Villette in Paris.",
		"1981 – Richard Serra installs Tilted Arc in the Federal Plaza in New York City. The sculpture was removed in 1989.",
		"1980 – Santa Monica Place was constructed by Frank Gehry.",
		"1979 – Charles Moore designs the Piazza d'Italia in New Orleans.",
		"1978 – Charles Eames dies.",
		"1977 – Frank Gehry redesigns his own house in Santa Monica, California.",
		"1976 – The Barbican Estate, designed by Chamberlin, Powell and Bon, opens in the City of London.",
		"1976 – The CN Tower in Toronto opens as the tallest freestanding structure on land.",
		"1975 – Completion of the Seoul Tower in Seoul, South Korea.",
		"1974 – National Assembly Building in Dakka, Bangladesh, is completed.",
		"1973 – The World Trade Center towers, designed by Minoru Yamasaki, are opened in New York.",
		"1972 – The Transamerica Pyramid in San Francisco, California, designed by William Pereira, is completed.",
		"1971 – Rothko Chapel in Houston, Texas, designed by Mark Rothko and Philip Johnson is completed.",
		"1970 – Construction begins on the Sears Tower in Chicago, designed by Bruce Graham and Fazlur Khan (of Skidmore, Owings & Merrill).",
		"1969 – Ludwig Mies van der Rohe and Walter Gropius die.",
		"1968 – Mies van der Rohe's New National Gallery in Berlin finished.",
		"1967 – Expo 67 in Montreal features the American pavilion, a geodesic dome designed by Buckminster Fuller, and the Habitat 67 housing complex designed by Moshe Safdie.",
		"1966 – The Gateway Arch by Eero Saarinen is finished in St. Louis, Missouri.",
		"1965 – NASA's Cape Canaveral VAB, the Niagara Skylon Tower, Philadelphia's LOVE Park, the Tel-Aviv Shalom Meir tower and the Salk Institute all open.",
		"1964 – The Unisphere heads New York World's Fair.",
		"1963 – The Palace of Assembly at Chandigarh, India, is finished.",
		"1962 – Orinda Orinda House & by Charles W. Moore is completed.",
		"1962 – Seattle Space needle & TWA Terminal by Saarinen at JFK are opened.",
		"1961 – Louis Kahn finishes the Richards Medical Building at the University of Pennsylvania in Philadelphia.",
		"1960 – Lucio Costa & Oscar Niemeyer plan buildings of Brasilia, new capital of Brazil.",
		"1959 – Frank Lloyd Wright's Guggenheim Museum in New York City is finished after 16 years of work on the project.",
		"1958 – The Seagram Building in New York designed by Ludwig Mies van der Rohe and Philip Johnson is completed.",
		"1957 – The Interbau 57 exposition in Berlin features structures by Alvar Aalto, Walter Gropius and his The Architects' Collaborative (TAC), and an unité by Le Corbusier.",
		"1956 – Crown Hall at the Illinois Institute of Technology, Chicago, designed by Mies van der Rohe, is finished.",
		"1955 – Completion of Le Corbusier's Notre Dame du Haut chapel at Ronchamp, France.",
		"1954 – Louis Kahn finishes his Yale University Art Gallery in New Haven, Connecticut, USA.",
		"1953 – Completion of the United Nations Headquarters in New York by a design team headed by Wallace Harrison and Max Abramowitz.",
		"1952 – Le Corbusier completes his Unité d'Habitation in Marseilles.",
		"1951 – Mies van der Rohe's Lake Shore Drive Apartments completed in Chicago.",
		"1950 – Eames House completed in Santa Monica, California, designed by Charles and Ray Eames.",
		"1949 – Glass House in New Canaan, Connecticut designed by Philip Johnson.",
		"1948 – Pietro Belluschi completes the Equitable Building in Portland, Oregon.",
		"1947 – Alvar Aalto builds the Baker House dormitories at the Massachusetts Institute of Technology.",
		"1946 – Le Corbusier draws up plans for La Rochelle-La Pallice, while his efforts to redesign Saint-Dié-des-Vosges (both cities in France) are foiled.",
		"1945 – John Entenza launches the Case Study Houses Program through his post as editor of Arts & Architecture magazine.",
		"1944 – Frank Lloyd Wright builds the research tower for his Johnson Wax Headquarters in Racine, Wisconsin.",
		"1943 – Oscar Niemeyer completes his Pampulha project in Brazil.",
		"1942 – Vichy rejects Le Corbusier's Obus E plan for Algiers.",
		"1941 – Le Corbusier offers his services to the Vichy regime.",
		"1940 – Peter Behrens dies.",
		"1939 – The 1939 World's Fair in New York includes the Finnish Pavilion by Alvar Aalto and the Brazilian Pavilion by Lucio Costa and Oscar Niemeyer.",
		"1938 – Frank Lloyd Wright purchases 800 acres (3.2 km2) of land 26 miles away from Phoenix, and begins to build Taliesin West, his winter home, in Scottsdale, Arizona, USA",
		"1937 – Wright completes his house Fallingwater, at Bear Run, Pennsylvania.",
		"1936 – Frank Lloyd Wright designs his monumental inward-looking Johnson Wax Headquarters in Racine, Wisconsin, USA.",
		"1935 – Cass Gilbert's United States Supreme Court Building is posthumously finished.",
		"1934 – Frank Lloyd Wright draws up plans for his Broadacre City, a decentralized urban metropolis.",
		"1933 – The Bauhaus closes under Nazi pressure.",
		"1932 – The Museum of Modern Art (MoMA) in New York holds its exhibition on modern architecture, coining the term 'International Style.'",
		"1931 – The Empire State Building, designed by Shreve, Lamb and Harmon, becomes the tallest building in the world.",
		"1930 – William Van Alen completes the Chrysler Building, an Art Deco skyscraper in New York City, USA.",
		"1929 – Barcelona Pavilion designed by Ludwig Mies van der Rohe.",
		"1929 – Villa Savoye designed by Le Corbusier.",
		"1928 – Hector Guimard builds his last house in Paris.",
		"1927 – The Weissenhof Estate, an exhibition of apartment houses designed by leading modern architects, held at Stuttgart, Germany.",
		"1926 – Antoni Gaudí and Louis Majorelle die.",
		"1925 – Bauhaus at Dessau designed by Walter Gropius.",
		"1924 – Gerrit Rietveld completes the Schröder House in Utrecht.",
		"1923 – Le Corbusier publishes Vers une architecture (Toward an Architecture), a summary of his ideas.",
		"1922 – Monument to the Third International designed by Vladimir Tatlin (unbuilt).",
		"1921 – Frank Lloyd Wright completes his Hollyhock House for Aline Barnsdall in Los Angeles, begun in 1917.",
		"1920 – The Einstein Tower in Potsdam, designed by Erich Mendelsohn, is completed.",
		"1919 – Construction begins on Howell Lewis Shay and Julian Abele's Philadelphia Museum of Art.",
		"1918 – Birth of Jørn Utzon, designer of the Sydney Opera House.",
		"1917 – Georges Biet's Art Nouveau house and apartment building in Nancy, Meurthe-et-Moselle is severely damaged by combat shells, but will be rebuilt nearly exactly as before in 1922.",
		"1916 – De Stijl movement founded in the Netherlands.",
		"1915 – Le Corbusier completes studies for his Dom-ino Houses.",
		"1914 – Walter Gropius designs his Fagus Factory.",
		"1913 – Cass Gilbert completes the Woolworth Building in New York.",
		"1912 – Frank Lloyd Wright begins work on the Avery Coonley Playhouse, Riverside, Illinois.",
		"1911 – Josef Hoffmann completes the Palais Stoclet in Brussels.",
		"1910 – Gaudí finishes the Casa Milà in Barcelona.",
		"1909 – Frank Lloyd Wright completes the Robie House near Chicago.",
		"1908 – Adolf Loos publishes his essay 'Ornament and Crime'.",
		"1907 – Gaudí completes the Casa Batlló in Barcelona.",
		"1906 – Lucien Weissenburger completes his own house, a striking example of the Art Nouveau style in Nancy, Meurthe-et-Moselle.",
		"1905 – Wright designs Unity Temple in Oak Park, Illinois.",
		"1904 – Otto Wagner completes his Post Office Savings Bank Building in Vienna.",
		"1903 – Josef Hoffmann finishes the Moser House in Vienna.",
		"1902 – Otto Wagner's Viennese Stadtbahn railway system is completed.",
		"1901 – John McArthur, Jr., completes the Second Empire-style Philadelphia City Hall, the world's tallest masonry building.",
		"1900 – The Gare d'Orsay, now the famous Musée d'Orsay, is built in Paris by Victor Laloux.",
		"1899 – Hector Guimard is commissioned to design the edicules for the Paris Métropolitain, which have become a hallmark of Art Nouveau design.",
		"1898 – Victor Horta designs his own house, now the Horta Museum.",
		"1897 – Hendrik Berlage designs his Amsterdam Stock Exchange.",
		"1896 – Eugène Vallin completes his own house and studio in Nancy (France), which is the first of many Art Nouveau structures built there by the members of the École de Nancy.",
		"1895 – The Biltmore Estate, the largest house in the USA, is completed for the Vanderbilt family in Asheville, North Carolina.",
		"1894 – Louis Sullivan builds the Guaranty Building in Buffalo, NY, USA.",
		"1893 – Victor Horta builds what is widely considered the first full-fledged Art Nouveau structure, the Hôtel Tassel, in Brussels.",
		"1892 – Modernist architect Richard Neutra is born.",
		"1891 – Louis Sullivan completes his Wainwright Building in Saint Louis.",
		"1890 – Louis Sullivan and Dankmar Adler build the Auditorium Building in Chicago.",
		"1889 – The 1889 Paris exhibition showcases some of the new technologies of iron, steel, and glass, including the Eiffel Tower.",
		"1888 – The Exposición Universal de Barcelona (1888) displays many buildings by Lluís Domènech i Montaner and other Catalan architects.",
		"1887 – H. H. Richardson's Marshall Field Store in Chicago is completed.",
		"1886 – Ludwig Mies van der Rohe is born.",
		"1885 – William Le Baron Jenney builds the first metal-frame skyscraper, the Home Insurance Building, in Chicago.",
		"1884 – Gaudí is given the commission for the Sagrada Família in Barcelona, which he will work on until 1926.",
		"1883 – Antoni Gaudí completes his Casa Vicens in Barcelona.",
		"1881 – The Natural History Museum in London opens.",
		"1880 – Cologne Cathedral is finally completed after 632 years.",
		"1879 – Louis Sullivan joins Dankmar Adler's firm in Chicago.",
		"1878 – Work begins on the Herrenchiemsee in Bavaria, designed by Georg Dollman.",
		"1877 – St Pancras railway station in London, by Sir George Gilbert Scott, is completed.",
		"1876 – Construction is finished on the Bayreuth Festspielhaus, designed by Gottfried Semper.",
		"1875 – The Opéra Garnier is completed in Paris.",
		"1874 – Completion of the California State Capitol in Sacramento, California.",
		"1873 – Scots' Church in Melbourne, Australia is finished.",
		"1872 – The Albert Memorial in London, designed by Sir George Gilbert Scott, is opened.",
		"1871 – The Great Chicago Fire destroys most of the city, sparking a building boom there.",
		"1870 – Birth of Adolf Loos.",
		"1869 – Birth of Georges Biet.",
		"1868 – Peter Behrens is born.",
		"1868 – The Gyeongbokgung of Korea is reconstructed.",
		"1867 – Frank Lloyd Wright is born. William Le Baron Jenney opens his architectural practice in Chicago.",
		"1866 – Completion of the St Pancras Hotel in London by Sir George Gilbert Scott.",
		"1865 – Birth of French architect Paul Charbonnier.",
		"1864 – French Art Nouveau architect Jules Lavirotte is born.",
		"1863 – U. S. Capitol building dome in Washington, D.C., is completed.",
		"1862 – Construction begins on Henri Labrouste's reading room at the Bibliothèque Nationale de France (site Richelieu).",
		"1861 – Victor Horta is born.",
		"1860 – Construction on Longwood, the largest octagonal residence in the USA, is begun in Natchez, Mississippi.",
		"1859 – Birth of Louis Majorelle and Cass Gilbert.",
		"1858 – The competition to design Central Park in New York is won by Frederick Law Olmsted and Calvert Vaux.",
		"1857 – Founding of the American Institute of Architects.",
		"1856 – Louis Sullivan and Eugène Vallin are born.",
		"1855 – The Palais d'Industrie is built for the World's Fair in Paris.",
		"1853 – Baron Haussmann becomes prefect of the Seine département and begins his vast urban renovations of Paris.",
		"1852 – Antoni Gaudí is born.",
		"1851 – The Crystal Palace designed by Joseph Paxton.",
		"1850 – Lluis Domènech í Montaner and John W. Root are born.",
		"1849 – John Ruskin's The Seven Lamps of Architecture is published.",
		"1848 – Construction begins on the Washington Monument in Washington, D.C., though it will not be completed until 1885.",
		"1847 – 24 August, birth of Charles Follen McKim (died 1909).",
		"1846 – 4 September, birth of Daniel Burnham of the firm Burnham and Root.",
		"1845 – Trafalgar Square in London, designed by Charles Barry and John Nash, is completed.",
		"1844 – Uspensky Cathedral in Kharkiv, Ukraine is completed.",
		"1843 – Construction begins on Henri Labrouste's Bibliothèque Sainte-Geneviève in Paris.",
		"1842 – The Église de la Madeleine is finally consecrated in Paris as a church.",
		"1841 – Birth of Otto Wagner.",
		"1840 – Construction begins on the Houses of Parliament in London, designed by Sir Charles Barry and Augustus Welby Northmore Pugin.",
		"1839 – Birth of Frank Furness in Philadelphia.",
		"1838 – Rideau Hall is built by Scottish architect Thomas McKay.",
		"1837 – The Royal Institute of British Architects (RIBA) is founded.",
		"1836 – A.W.N. Pugin publishes his Contrasts, a treatise on the morality of Catholic, Gothic architecture.",
		"1835 – The New Orleans Mint, Dahlonega Mint, and Charlotte Mint are all designed by William Strickland and begin producing. coins in three years.",
		"1834 – Alfred B. Mullet, designer of both the San Francisco and the Carson City Mints in the USA, is born in Britain.",
		"1833 – William Strickland completes the first Philadelphia Mint building.",
		"1832 – William Le Baron Jenney is born.",
		"1830 – The Altes Museum in Berlin, designed by Karl Friedrich Schinkel, is completed after seven years of construction.",
		"1829 – The panopticon-design Eastern State Penitentiary in Philadelphia, designed by John Havilland, opens.",
		"1828 – Completion of the Marble Arch in London, designed by John Nash.",
		"1827 – William Burges, Gothic Revival architect in Britain, is born.",
		"1826 – The Menai Suspension Bridge over the Menai Strait, in Wales, designed by Thomas Telford, is completed.",
		"1825 – The front and rear porticoes of the White House are added to the building.",
		"1824 – The Shelbourne Hotel in Dublin, Ireland is completed.",
		"1823 – Work begins on the British Museum in London, designed by (Sir) Robert Smirke.",
		"1822 – Birth of landscape architect Frederick Law Olmsted.",
		"1821 – Karl Friedrich Schinkel completeds his Schauspielhaus in Berlin and Benjamin Latrobe's Baltimore Basilica is completed.",
		"1820 – Death of Benjamin Latrobe.",
		"1819 – Birth of English architect Horace Jones.",
		"1818 – Birth of American architect James Renwick, Jr.",
		"1817 – Dulwich Picture Gallery in London is designed by Sir John Soane as the first purpose-built art gallery.",
		"1816 – Regent's Bridge, crossing the River Thames in central London, designed by James Walker, is opened.",
		"1815 – Brighton Pavilion is redesigned by John Nash for the future King George IV.",
		"1814 – British troops burn the White House in Washington, D.C., gutting it completely.",
		"1813 – Death of Alexandre-Théodore Brongniart.",
		"1812 – The Egyptian Hall in London, designed by P. F. Robinson, is completed.",
		"1811 – The United States Capitol, designed by Benjamin Latrobe, is completed.",
		"1810 – Old Saint Petersburg Stock Exchange, designed by Jean-François Thomas de Thomon, is completed.",
		"1809 – Birth of city planner Baron Haussmann.",
		"1808 – Construction begins on the Paris Bourse, designed by Alexandre-Théodore Brongniart.",
		"1807 – The Templo de Nuestra Señora del Carmen in Celaya, Guanajuato, Mexico is completed.",
		"1806 – Arc de Triomphe, Paris from Jean Chalgrin commissioned by Napoleon Bonaparte.",
		"1805 – The Ellesmere Canal, designed by Thomas Telford, is completed.",
		"1804 – Completion of the Government House in the Bahamas.",
		"1803 – The Raj Bhavan in Kolkata, West Bengal, India is finished.",
		"1802 – The Temple of Saint Philip Neri in Guadalajara, Jalisco, Mexico is completed.",
		"1801 – Birth of Henri Labrouste.",
		"1800 – The White House in Washington D.C. is completed by team of client George Washington, planner Pierre L'Enfant, and architect James Hoban.",
		"1799 – Death of French neoclassicist Étienne-Louis Boullée.",
		"1798 – Karlsruhe Synagogue, usually regarded as the first building of the Egyptian Revival architecture, built by Friedrich Weinbrenner in Karlsruhe.",
		"1797 – Ditherington Flax Mill, in Shrewsbury, England, the world's oldest surviving iron-framed building, is completed.",
		"1796 – Somerset House in London, designed by William Chambers, is completed.",
		"1795 – Birth of English architect Charles Barry.",
		"1794 – Hwaseong Fortress in Suwon, Korea, begins.",
		"1793 – Old East, the oldest public university building in the USA, is erected on the campus of the University of North Carolina at Chapel Hill.",
		"1792 – Sir John Soane begins work on his house in London, later Sir John Soane's Museum.",
		"1789 – Jacques-Germain Soufflot's Panthéon in Paris is completed by his student Jean-Baptiste Rondelet.",
		"1786 – Schloss Bellevue in Berlin, designed by Philipp Daniel Boumann, is completed.",
		"1782 – Alexandre-Théodore Brongniart is named architect and controller-general of the École Militaire in Paris.",
		"1780 – 29 August – Death of Jacques-Germain Soufflot (b. 1713).",
		"1768 – Petit Trianon at Versailles is completed.",
		"1767 – Arg of Karim Khan",
		"1766 – Horace Walpole's Strawberry Hill House in London is completed.",
		"1764 – Construction begins on church of La Madeleine, Paris.",
		"1753 – The Georgian-Style Pennsylvania State House, (Independence Hall) is completed in Philadelphia, Pennsylvania.",
		"1750 –Ahom momuments -rangghar in easternindia.",
		"1743 – The Dresden Frauenkirche, Dresden, Germany, is completed.",
		"1739 – Alexandre-Théodore Brongniart is born.",
		"1735 – Buckingham Palace built",
		"1729 – Christ Church, Spitalfields in London is completed.",
		"1726 – The remaining ruins of Liverpool Castle are demolished.",
		"1724 – The construction of Blenheim Palace is completed.",
		"1723 – Mavisbank House in Loanhead, Scotland is designed.",
		"1708 – St. Paul's Cathedral in London, designed by Christopher Wren, is completed.",
		"1705 – November: In Williamsburg, capital of the Virginia colony in America, construction of the Capitol building is completed.",
		"1704 – St Magnus-the-Martyr in London is completed.",
		"1702 – The Thomaskirche in Leipzig, Germany is completed."
		/*"1690s – Potala Palace is completed in Tibet.",
		"1690s – The city of Noto, Italy, on Sicily, is devastated by an earthquake (1693), and a rebuilding program begins in the Baroque style.",
		"1680s – Church of Les Invalides, Paris is built by Jules Hardouin-Mansart.",
		"1670s – The Royal Greenwich Observatory in London, designed by Christopher Wren is completed (1676).",
		"1660s – Louis XIV, with the architect Jules Hardouin-Mansart, begins to enlarge the Palace of Versailles (1661).",
		"1650s – Completion of the church Sant'Agnese in Agone in Rome, designed by Borromini and Carlo Rainaldi.",
		"1640s – Borromini builds the church Sant'Ivo alla Sapienza in Rome.",
		"1630s – Emperor Shah Jahan construct Taj Mahal in Agra, India.",
		"1630s – Borromini builds the church San Carlo alle Quattro Fontane in Rome.",
		"1620s – St. Peter's Basilica is completed in Vatican City (1626).",
		"1610s – Mohammadreza Isfahani builds Naghsh-i Jahan Square in Isfahan, Iran.",
		"1600s – 33 pol bridge is constructed in Isfahan, Iran.",
		"1590s – Bernini and Borromini are born.",
		"1560s – work begins on Palladio's Villa Capra 'La Rotonda'.",
		"1530s – Work begins on Michelangelo's Piazza del Campidoglio (Capitoline Hill).",
		"1510s – Construction begins on Chateau Chambord.",
		"1500s – Construction begins on St. Peter's Basilica. Andrea Palladio is born.",
		"1480s – Vitruvius' treatise De architectura and Leon Battista Alberti's De re aedificatoria were published, having previously existed only in manuscript.",
		"1420s – The Forbidden City of China is completed",
		"1400s – The Changdeokgung of Korea is completed.",
		"1260s – Fakr ad-Din Mosque is finished in the Sultanate of Mogadishu",
		"1240s – The foundation stone of Cologne Cathedral in Cologne is laid.",
		"1190s – Construction of Qutub Minar started in India",
		"1190s – Construction begins on the present form of Chartres Cathedral after a fire.",
		"1140s – Abbot Sugar supervises the reconstruction of St. Denis in the Gothic style",
		"1130s – Work begins on the Basilique Saint-Denis in France.",
		"1100s – Yingzao Fashi written by Li Jie published during mid Song Dynasty, an important set of building standards.",
		"1090s – Durham Cathedral founded",
		"1070s – St Albans Cathedral commenced; built from the ruins of Roman Verulamium.",
		"1050s – Greensted Church built, oldest surviving church (extensively repaired) in the world, possibly the oldest wooden building in Europe.",
		"1030s – Gangaikonda Cholapuram built by the kingdom of Rajendra Chola I under Chola dynasty @ Tamil Nadu, South India. Granite Stone Structure. No Wooden & Metal parts used in structure",
		"1000s – Brihadeeswarar Temple built by the kingdom of Raja Raja Chola I under Chola dynasty @ Tamil Nadu, South India. Granite Stone Structure. No Wooden & Metal parts used in structure",
		"0905 – Aachen Cathedral consecrated. Major renovations in the 10th Century.",
		"0900s – Akhtala monastery built, intended as a fortress.",
		"0848 San Miguel de Lillo built in the Austrian pre-romanesque style of Spain",
		"0700s – Seokguram of Korea is constructed.",
		"0600s – St. Hripsime Church, one of the world's oldest surviving churches, constructed.",
		"0500s – Hagia Sophia built in its present form. Oldest known surviving roof truss in Saint Catherine's Monastery.",
		"0495-0504 - Basilica of Sant'Apollinare Nuovo in Ravenna[1]",
		"0470 - Basilica of St. Martin[1]",
		"0432 - 40 St. Maria Maggiore.[1] and St. Sabina.[1]",
		"0400s – Mahabalipuram is an ancient port city of south east India construction was done by Mahendravarman I & his son Narasimhavarman I under Pallava Kingdom, Tamil Nadu, South India",
		"ca 0330 - St. Paul’s Outside the Walls.[1]",
		"0325 - Old St. Peters.[1]",
		"0320 - Construction of Archbasilica of St. John Lateran begun using standards that would be followed in future basilica designs.[1]",
		"0315 – Arch of Constantine deicated to the Battle of Milvian Bridge",
		"0312 - Basilica of Constantine [2] The brick audience basilica at Trier, the Aula Palatina completed.[2] Catacomb of the Via Latina begun.",
		"0307-0312 – Basilica of Maxentius [2] and",
		"0300s – Nalanda, an ancient center of higher learning, was built in Gupta Empire in India.",
		"0262 – Arch of Gallienus completed in Rome",
		"0231 – Dura-Europos church, in Syria. A house built c. 200 can converted into a Christian Church.[1]",
		"0224 – Dura-Europos synagogue one of the oldest synagogues.",
		"0211 – Arch of Drusus completed in Rome.",
		"0203 – Arch of Septimius Severus completed",
		"0212-0216 - Baths of Caracalla.[2] 296-306 Baths of Diocletian.[2]",
		"0193 - Column of Marcus Aurelius dedicated in Rome.",
		"0134 - Ponte Sant'Angelo completed across the Tiber in Rome.",
		"0118-1128 Pantheon, Rome is completed, an early full dome.[2]",
		"0113 – Trajan's Column dedicated in Rome.",
		"0104 - Alcántara Bridge is a Roman multiple arched bridge over the Tagus River in Spain.",
		"0082 - Arch of Titus an artifact from the ‘Temple Period’ and the beginning of the Jewish Diaspora."*/
    ]
}